config/routes.rb
Rails.application.routes.draw do
  get 'start/index'
  get 'root/index'
  get 'surveys/index'
  post 'surveys/start'
  get 'surveys/start'
  get 'surveys/question'
  post 'surveys/question'
  post 'surveys/answer'
  get 'surveys/answer'
  get 'surveys/end'

  root 'start#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
  end

  def start
    session.clear
    # @survey = Survey.new(params[:surveys])
    name = params[:name] 
    total = 21

    session[:current] ||= 1
    session[:yes] = 0
    session[:name] = name

    redirect_to :action => "question"
  end

  def question
    @questions = [
      '',
      'Saya pergi keluar rumah',
      'Saya menggunakan transportasi umum',
      'Saya idak pakai masker saat berkumpul dengan orang lain',
      'Saya berjabat tangan dengan orang lain',
      'Saya tidak membersihkan tangan sebelum pegang kemudi kendaraan',
      'Saya menyentuh benda yang di sentuh orang lain',
      'Saya tidak menjaga jarak 1,5 meter dengan orang lain ketika melakukan kegiatan diluar rumah',
      'Saya makan diluar rumah (warung/restaurant)',
      'Saya tidak minum air hangat, dan mencuci tangan dengan sabun setelah sampai di tujuan',
       'Saya berada di wilayah tempat pasien tertular',
       'Saya pasang hand sanitizer atau pencuci tangan di depan rumah',
       'Saya tidak mencuci tangan dengan sabun saat sampai rumah',
       'Saya tidak menyediakan tissue basah/antiseptik, handsanitizer, masker, dll untuk keluarga dirumah',
       'Saya tidak segera merendam pakaian bekas pakai dengan air hangat',
       'Saya tidak segera mandi setelah sampai dirumah',
       'Saya tidak mensosialisasikan check list penilaian resiko pribadi ini kepada keluarga dirumah',
       'Saya dalam sehari tidak kena cahaya matahari 15 menit',
       'Saya tidak olahraga minimal 30 menit sehari',
       'Saya jarang minum vitamin C & E, dan kurang tidur',
       'Usia saya diatas 60 tahun',
       'Saya mempunyai penyakit jantung/diabetes/gangguan pernafasan kronis'
    ]
    session[:name]
    session[:current]
    session[:yes]
    @total = 21

    if session[:current] >= @total
      redirect_to :action => "end"
      return
     end

     @question = @questions[session[:current]]

  end

  def answer
    session[:name]
    session[:current]
    total = 21

    pilihan = params[:choice]


    if pilihan == 'true'
      session[:yes] += 1
    end

    session[:current] += 1

    redirect_to :action => "question"
  end

  def end
    session[:yes]
    session[:name]
    
    if session[:yes] >= 15 
      @msg = "Resiko Tinggi"
    elsif session[:yes] >= 8
      @msg = "Resiko sedang"
    elsif session[:yes] < 8
      @msg = "Resiko rendah"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CovidSurvey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/start/index.html.erb
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Covid-Survey </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
		<link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

		<%= csrf_meta_tags %>
        <%= csp_meta_tag %>
            <%# <link rel="stylesheet" href="assets/css/bootstrap.min.css"> %>
            <%= stylesheet_link_tag 'bootstrap.min', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/owl.carousel.min.css"> %>
            <%= stylesheet_link_tag 'owl.carousel.min', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/flaticon.css"> %>
            <%= stylesheet_link_tag 'flaticon', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/slicknav.css"> %>
            <%= stylesheet_link_tag 'slicknav', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/animate.min.css"> %>
            <%= stylesheet_link_tag 'animate.min', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/magnific-popup.css"> %>
            <%= stylesheet_link_tag 'magnific-popup', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/fontawesome-all.min.css"> %>
            <%= stylesheet_link_tag 'fontawesome-all.min', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/themify-icons.css"> %>
            <%= stylesheet_link_tag 'themify-icons', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/slick.css"> %>
            <%= stylesheet_link_tag 'slick', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/nice-select.css"> %>
            <%= stylesheet_link_tag 'nice-select', media: 'all.js', 'data-turbolinks-track': 'reload' %>
            <%# <link rel="stylesheet" href="assets/css/style.css"> %>
            <%= stylesheet_link_tag 'style', media: 'all.js', 'data-turbolinks-track': 'reload' %>

            <%# -------------------------------------------------------------------------------------------- %>
           
   </head>

   <body>

    <main>

        <!-- Slider Area Start-->
        <div class="slider-area ">
            <div class="slider-active">
                <div class="single-slider slider-height slider-padding sky-blue d-flex align-items-center">
                    <div class="container">
                        <div class="row d-flex align-items-center">
                            <div class="col-lg-6 col-md-9 ">
                                <div class="hero__caption">
                                    <span data-animation="fadeInUp" data-delay=".4s">WELCOME</span>
                                    <h1 data-animation="fadeInUp" data-delay=".6s">Coronavirus<br>survey</h1>
                                    <p data-animation="fadeInUp" data-delay=".8s">“The greatest of failures is sacrificing health for another kind of happiness.”</p>
                                    <!-- Slider btn -->
                                   <div class="slider-btns">
                                        <!-- Hero-btn -->
                                        <%= link_to  "Start Survey", surveys_index_path, class: 'btn btn-radius' %>
                                        </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="hero__img d-none d-lg-block f-right" data-animation="fadeInRight" data-delay="1s">
                                    <%= image_tag 'hero/hero_right.png' %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
                            
        
    </body>
</html>

app/views/surveys/answer.html.erb
<h1>Surveys#answer</h1>
<p>Find me in app/views/surveys/answer.html.erb</p>

<h1>Question <%= session[:current]  %> of <%= @total %></h1>

<%= form_tag({:controller => "surveys", :action => "question"}) do %>
  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
<% end %>

app/views/surveys/end.html.erb
<div class="pricing-card-area">
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="single-card text-center mb-30">
                    <div class="card-top">
                        <div class="typography">
                          <h2><%= session[:name] %></h2><hr>
                        </div>
                      </div>
                    <div class="card-bottom">
                        <ul>       
                          <li>                                
                            <div class="mt-10">
                              <h4>Anda memiliki <%= @msg %> terinfeksi virus corona</h4> <br>
						      	        </div>
                          </li>
                          <li>
                              <%= link_to 'Finish', root_path, :class => "btn card-btn1" %>                          
                          </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/surveys/index.html.erb
<div class="pricing-card-area">
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="single-card text-center mb-30">
                  <%= form_tag({:controller => "surveys", :action => "start"}) do %>  
                    <div class="card-top">
                        <div class="typography">
                          <h2><%= label_tag :name, "Please enter your name" %></h2>
                        </div>
                      </div>
                    <div class="card-bottom">
                        <ul>       
                          <li>                                
                            <div class="mt-10">
                                <%= text_field_tag :name, " ", :class => 'single-input' %><br>
						  	            </div>
                          </li>
                        </ul>
                        <%= submit_tag "Start!", :class => "btn card-btn1"%>
                    </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/surveys/question.html.erb
<% content_for(:title) do %>
  Question <%= session[:current] + 1 %> of <%= @total %>
<% end %>
<div class="services-area">
		<div class="container mt-5">
			<div class="row d-flex justify-content-center">
				<div class="col-lg-8">
					<div class="section-tittle text-center mb-80">
						<h3>Question number <%= session[:current] %> of <%= @total %>​</h3> <hr> <br>
              <h1><%= @question %></h1> <br>

                <%= form_tag({:controller => "surveys", :action => "answer"}) do %>                                           <!--//-->
                <div class="row offset-md-5">
                  <div class="col-md-3 mt-5">
                    <div class="switch-wrap d-flex justify-content-between">
                    <h4><%= label_tag :choice, "Yes" %></h4>
                        <div class="col-mt-3">
                          <%= radio_button_tag 'choice', "true" %>                                      <!--//-->
                        </div>  
                    </div>
                    <div class="switch-wrap d-flex justify-content-between">
                    <h4><%= label_tag :choice, "No" %></h4>
                      <div class="col-mt-3">
                        <%= radio_button_tag 'choice', "false" %>                    <!--//-->
                      </div> 
                    </div>
                    <br>
                </div>
              </div>
              <div class="button-group-area mt-40">
                  <%= submit_tag("NEXT", :class => "genric-btn danger circle arrow") %>                             <!--//-->
              </div>
              <% end %>                                                           <!--//-->
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/surveys/start.html.erb
<h1>Surveys#start</h1>
<p>Find me in app/views/surveys/start.html.erb</p>